### ISSUE TITLE
optimisation

### ISSUE THREAD

**Issue by chessai** [chessai/aks#1]
@andrewthad it's possible that the optimisation of AKS will not show significant speedups until a sufficiently large lower bound. According to a friend, that upper bound is beyond the range of a machine word, though I have not verified this.

**Comment by andrewthad** [comment]
That's a bummer. It makes sense though. I think you said it has a runtime of `(log_2(n))^6`. When n is a trillion, that's still 40 ^ 6 or roughly 4e9. The naive algorithm has a runtime of `sqrt(n)`, and sqrt(1e12) = 1e6. So, even at a trillion, you're still around 4000x slower.

**Comment by chessai** [comment]
I guess all we need to do then is come up with a majour mathematical breakthrough.
